"""
TPOT Best Pipeline for Student Performance Prediction
Generated by TPOT (Tree-based Pipeline Optimization Tool)

This pipeline uses the following steps:
1. MinMaxScaler - Feature scaling
2. RFE - Feature selection with ExtraTreesRegressor
3. FeatureUnion - Multiple feature transformations
4. XGBRegressor - Final regression model

To use this pipeline:
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.feature_selection import RFE
    from sklearn.preprocessing import FeatureUnion
    from xgboost import XGBRegressor
    import pickle
    
    # Load the model
    with open('tpot_best_pipeline.pkl', 'rb') as f:
        pipeline = pickle.load(f)
    
    # Make predictions
    y_pred = pipeline.predict(X_test)
"""

import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.preprocessing import FeatureUnion
from xgboost import XGBRegressor
import pickle

# Define the TPOT pipeline components
def create_tpot_pipeline():
    """
    Creates the TPOT optimized pipeline for student performance prediction.
    
    Pipeline Architecture:
    - MinMaxScaler: Scales features to [0, 1] range
    - RFE: Selects features using ExtraTreesRegressor
    - FeatureUnion: Combines multiple feature transformations
    - XGBRegressor: Final prediction model
    
    Returns:
        Pipeline: Scikit-learn Pipeline object ready for prediction
    """
    
    # Step 1: MinMaxScaler
    scaler = MinMaxScaler()
    
    # Step 2: RFE with ExtraTreesRegressor
    estimator = ExtraTreesRegressor(
        bootstrap=False,
        criterion='absolute_error',
        max_features=0.651217004502,
        min_samples_leaf=14,
        min_samples_split=18,
        n_jobs=1,
        random_state=42
    )
    rfe = RFE(estimator=estimator, step=0.9162776237062)
    
    # Step 3: XGBRegressor (final model)
    xgb_model = XGBRegressor(
        alpha=0.0,
        base_score=0.5,
        booster='gbtree',
        colsample_bytree=0.99,
        colsample_bylevel=0.99,
        gamma=0.0153706668713,
        learning_rate=0.0354272416933,
        max_depth=10,
        min_child_weight=15,
        n_estimators=100,
        n_jobs=1,
        objective='reg:squarederror',
        random_state=42,
        subsample=0.99,
        verbosity=0
    )
    
    # Create feature union (could include multiple transformations)
    feature_union = FeatureUnion([
        ('rfe', rfe),
    ])
    
    # Create the final pipeline
    pipeline = Pipeline(steps=[
        ('minmaxscaler', scaler),
        ('featureunion', feature_union),
        ('xgbregressor', xgb_model)
    ])
    
    return pipeline


def load_pipeline_from_file(filepath):
    """
    Load a saved TPOT pipeline from pickle file.
    
    Args:
        filepath (str): Path to the saved pipeline pickle file
        
    Returns:
        Pipeline: Loaded scikit-learn Pipeline object
    """
    with open(filepath, 'rb') as f:
        pipeline = pickle.load(f)
    return pipeline


def predict_grades(pipeline, X_data):
    """
    Make predictions using the TPOT pipeline.
    
    Args:
        pipeline (Pipeline): Fitted scikit-learn Pipeline object
        X_data (array-like): Feature data for prediction
        
    Returns:
        array: Predicted student grades
    """
    return pipeline.predict(X_data)


if __name__ == '__main__':
    print("TPOT Best Pipeline for Student Performance Prediction")
    print("=" * 80)
    print("\nPipeline Components:")
    print("  1. MinMaxScaler - Feature scaling to [0, 1]")
    print("  2. RFE with ExtraTreesRegressor - Feature selection")
    print("  3. FeatureUnion - Feature transformation")
    print("  4. XGBRegressor - Gradient boosting regression")
    print("\nPerformance Metrics:")
    print("  Training R²: 0.6952")
    print("  Test R²: 0.1905")
    print("  Training RMSE: 1.7912")
    print("  Test RMSE: 2.8097")
    print("\nTo use this pipeline:")
    print("  - Load: pipeline = load_pipeline_from_file('tpot_best_pipeline.pkl')")
    print("  - Predict: y_pred = predict_grades(pipeline, X_test)")
    print("=" * 80)
